export const LOAD_FILE = 'LOAD_FILE'
export const REPLACE_LOG_FILE = 'REPLACE_LOG_FILE'
export const CLOSE_LOG_FILE = 'CLOSE_LOG_FILE'

export const SET_FILTERS = 'SET_FILTERS'
export const ADD_FILTER = 'ADD_FILTER'
export const UPDATE_FILTER = 'UPDATE_FILTER'
export const DELETE_FILTER = 'DELETE_FILTER'
export const UP_FILTER = 'UP_FILTER'
export const DOWN_FILTER = 'DOWN_FILTER'